services:
  kibana:
    type: compose
    services:
      image: "docker.elastic.co/kibana/kibana:7.17.0"
      command: "/bin/tini -- /usr/local/bin/kibana-docker"
      user: kibana
      ports:
        - "5601:5601"

proxy:
  kibana:
    - kibana.lndo.site:5601
